# Generated by Django 5.1.1 on 2024-09-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supreme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
    ]
